[package]
name = "rust-notifications"
description = "Library for sending iOS and Android push notifications"
homepage = "https://comm.app"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
tracing = "0.1"
tokio = { version = "1.14", features = ["full"]}
lazy_static = "1.4"
a2 = "0.6"

[lib]
crate-type=["staticlib"]
