version: "3.9"
services:
  node:
    build:
      dockerfile: keyserver/Dockerfile
      context: ../
    image: commapp/node-keyserver:1.0
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://cache
    depends_on:
      - cache
  cache:
    image: redis:6.2.6-bullseye
    restart: always
    expose:
      - "6379"
    command: redis-server --loglevel warning
