version: "3.9"
services:
  node:
    build:
      dockerfile: keyserver/Dockerfile
      context: ../
    image: commapp/node-keyserver:1.0
    container_name: node-keyserver
    ports:
      - "3000:3000"
