version: "3.9"
services:
  node:
    build:
      dockerfile: keyserver/Dockerfile
      context: ../
    image: commapp/node-keyserver:1.0
    restart: always
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://cache
    depends_on:
      - cache
      - database
  database:
    image: mysql:5.7.37-debian
    restart: always
    expose:
      - "3306"
    # There is no M1 build on Docker Hub, so we force x64
    # This is what we want in production anyways. M1 devs will have it emulated
    platform: linux/amd64
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
  cache:
    image: redis:6.2.6-bullseye
    restart: always
    expose:
      - "6379"
    command: redis-server --loglevel warning
