version: "3.9"
services:
  node:
    build:
      dockerfile: keyserver/Dockerfile
      context: ../
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    image: commapp/node-keyserver:1.0
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://cache
      - COMM_LISTEN_ADDR=0.0.0.0
      - COMM_DATABASE_HOST=${COMM_DATABASE_HOST:-database}
      - COMM_DATABASE_DATABASE
      - COMM_DATABASE_USER
      - COMM_DATABASE_PASSWORD
    depends_on:
      - cache
      - database
  database:
    image: mysql:5.7.37-debian
    restart: always
    expose:
      - "3306"
    # There is no ARM-based Mac build on Docker Hub, so we force x64
    # This is what we want in production anyways. ARM-based Mac devs will have
    # it emulated
    platform: linux/amd64
    command: >
      --max-allowed-packet=64M
      --local-infile=0
      --sql-mode=STRICT_ALL_TABLES
      --innodb-buffer-pool-size=1600M
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=$COMM_DATABASE_DATABASE
      - MYSQL_USER=$COMM_DATABASE_USER
      - MYSQL_PASSWORD=$COMM_DATABASE_PASSWORD
    volumes:
      - mysqldata:/var/lib/mysql
  cache:
    image: redis:6.2.6-bullseye
    restart: always
    expose:
      - "6379"
    command: redis-server --loglevel warning
volumes:
  mysqldata:
