version: "3.9"
services:
  node:
    build:
      dockerfile: keyserver/Dockerfile
      context: ../
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    image: commapp/node-keyserver:1.0
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://cache
      - COMM_LISTEN_ADDR=0.0.0.0
      - COMM_MYSQL_HOST=${COMM_MYSQL_HOST:-database}
      - COMM_MYSQL_DATABASE
      - COMM_MYSQL_USER
      - COMM_MYSQL_PASSWORD
    depends_on:
      - cache
      - database
  database:
    image: mariadb:10.7.4-focal
    restart: always
    expose:
      - "3306"
    command: >
      --max-allowed-packet=64M
      --local-infile=0
      --sql-mode=STRICT_ALL_TABLES
      --innodb-buffer-pool-size=1600M
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=$COMM_MYSQL_DATABASE
      - MARIADB_USER=$COMM_MYSQL_USER
      - MARIADB_PASSWORD=$COMM_MYSQL_PASSWORD
    volumes:
      - mysqldata:/var/lib/mysql
  cache:
    image: redis:6.2.6-bullseye
    restart: always
    expose:
      - "6379"
    command: redis-server --loglevel warning
volumes:
  mysqldata:
