[package]
name = "identity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.6"
prost = "0.9"
futures-core = "0.3"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
opaque-ke = "1.2.0"
argon2 = "0.3"
curve25519-dalek = "3"
sha2 = "0.9"
digest = "0.9"

[build-dependencies]
tonic-build = "0.6"
