[package]
name = "identity"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.6"
prost = "0.9"
futures-core = "0.3"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
opaque-ke = "1.2.0"
argon2 = "0.3"
curve25519-dalek = "3"
sha2 = "0.9"
digest = "0.9"
clap = { version = "3.1.12", features = ["derive"] }

[build-dependencies]
tonic-build = "0.6"
