steps:
  - command:
      - 'yarn cleaninstall --frozen-lockfile --skip-optional'
      - 'cd native/android && ./gradlew clean'
      - './gradlew bundleRelease "-Dorg.gradle.jvmargs=-Xmx32g -XX:MaxPermSize=32g -XX:+HeapDumpOnOutOfMemoryError"'
    agents:
      - 'android=true'
