steps:
  - label: "CMake Lint (Nix)"
    command: >
      nix shell github:nixos/nixpkgs?ref=nixos-22.05#cmake-format
      --extra-experimental-features "nix-command flakes"
      -c cmake-lint **/CMakeLists.txt
    plugins:
      - docker#v3.13.0:
          image: 'nixos/nix:latest'
    agents:
      - 'autoscaling=true'
