steps:
  - command:
      - '(pkill flow || true)'
      - 'yarn cleaninstall --frozen-lockfile --skip-optional'
      - 'yarn eslint --max-warnings=0 & yarn workspace lib flow & yarn workspace web flow & yarn workspace landing flow & yarn workspace native flow & yarn workspace keyserver flow'
      - 'yarn workspace lib test && yarn workspace keyserver test'
    agents:
      - 'linux=true'
