[package]
name = "commtest"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.6"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
prost = "0.9"
futures = "0.1"
async-stream = "0.3.2"

[build-dependencies]
tonic-build = "0.6"
