name: ESLint & Flow & Jest

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm install -g yarn
        run: npm install -g yarn

      - name: yarn --frozen-lockfile
        run: yarn --frozen-lockfile

      - name: yarn eslint --max-warnings=0
        run: yarn eslint --max-warnings=0

      - name: '[lib] flow'
        working-directory: ./lib
        run: ./node_modules/.bin/flow

      - name: '[keyserver] flow'
        working-directory: ./keyserver
        run: ./node_modules/.bin/flow

      - name: '[web] flow'
        working-directory: ./web
        run: ./node_modules/.bin/flow

      - name: '[landing] flow'
        working-directory: ./landing
        run: ./node_modules/.bin/flow

      - name: '[native] flow'
        working-directory: ./native
        run: ./node_modules/.bin/flow

      - name: '[lib] test'
        working-directory: ./lib
        run: yarn test

      - name: '[keyserver] test'
        working-directory: ./keyserver
        run: yarn test
