name: Services CI

on:
  push:
    branches: [master]
    paths-ignore:
      - 'landing/**'
      - 'web/**'
      - 'docs/**'
      - 'keyserver/**'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Yarn
        run: npm install -g yarn

      - name: yarn --frozen-lockfile
        run: yarn --frozen-lockfile

      - name: Build Services
        working-directory: ./services
        run: yarn build-all

      - name: Test Tunnelbroker service
        working-directory: ./services
        run: yarn test-tunnelbroker-service

      - name: Test Backup service
        working-directory: ./services
        run: yarn test-backup-service

      - name: Test Blob service
        working-directory: ./services
        run: yarn test-blob-service
